export interface TankProperties {
    private_label: string,
    oem: string,
    colloquial_name: string,
    material: string,
    finish: string,
    capacity: number,
    volume: number,
    rated_pressure: number,
    manufacture_years: string,
    height: number,
    diameter: number,
    weight_empty: number,
    weight_full: number,
    buoyancy_empty: number,
    buoyancy_full: number,
    valve_type: string,
    ree: number,
    _source: string
}